applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

app_name='persona_app'

urlpatterns = [
    path('listar-todo-empleado/', views.ListAllEmpleados.as_view(),name='empleados_all'),
    path('listar-by-area/<shor_name>/', views.ListbyArea.as_view(),name='empleados_area'),
    path('listar-empleados-admin/', views.ListaEmpleadosAdmin.as_view(),name='empleados_admin'),
    path('buscar-empleado/', views.listEmpleadoByKword.as_view()),
    path('listar-habilidades-empleado/', views.HabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(),name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(),name='empleado_add'),
    path('success/', views.SuccessView.as_view(),name='correcto'),
    path('update-empleado/<pk>', views.EmpleadoUpdateView.as_view(),name='modificar_empleado'),
    path('delete-empleado/<pk>', views.EmpleadoDeleteView.as_view(),name='eliminar_empleado'),
    path('', views.InicioView.as_view(),name='inicio'),
    

    
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    ##incluimos las URL de la APP DEPARTAMENTO

    re_path('',include('applications.departamento.urls')),
    re_path('',include('applications.home.urls')),
    re_path('',include('applications.persona.urls')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento
# Create your models here.
 
class Habilidades(models.Model):
    habilidad=models.CharField('Habilidad',max_length=50)

    class meta:
        verbose_name='Habilidad'
        verbose_name_plural='Habilidad de Empleado'


    def __str__(self):
        return str(self.id) + '-' +self.habilidad


class Empleado(models.Model):
        #"""Modelo para tabla empelado"""


    JOB_CHOICES =(
        ('0','CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2','ECONOMISTA'),
        ('3','OTRO'),
        )
            #Contador
            #Administrador
            #Economista
            #otro
        
    first_name = models.CharField('Nombres',max_length=50)
    last_name = models.CharField('Apellidos',max_length=50)
    full_name = models.CharField('Nombres Completos',max_length=120,blank=True)
    job=models.CharField('Trabajo',max_length=50,choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True ,null=True)
    habilidades = models.ManyToManyField(Habilidades)


    class Meta:
        verbose_name = 'Mi Empleado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['-first_name', 'last_name']
        unique_together = ('first_name', 'departamento')

    def __str__(self):
        return str(self.id) + '.' + self.first_name + '-' +self.last_name

applications/persona/forms.py
from django import forms

from .models import Empleado


class EmpleadoForm(forms.ModelForm):
    
    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/persona/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, CreateView,DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from .models import Empleado

# Create your views here.
# models
from .models import Empleado
# forms
from .forms import EmpleadoForm


class InicioView(TemplateView):
    """ vista que carga la pagina de inicio """
    template_name = 'inicio.html'
    

class ListAllEmpleados(ListView):
    template_name='persona/list_all.html'
    paginate_by=4
    ordering='first_name'
    model=Empleado
    context_object_name='empleados'
    def get_queryset(self):
        
        palabra_clave=self.request.GET.get("kword",'')
        
        lista=Empleado.objects.filter(
            
                first_name__icontains=palabra_clave
        )
        print('lista resultado :',lista)
        return lista


class ListbyArea(ListView):
    """Lista empleados de un Area"""
    template_name='persona/list_by_area.html'
    context_object_name='empleados'     

    def get_queryset(self):
        area=self.kwargs['shor_name']
        lista=Empleado.objects.filter(
            departamento__shor_name =area
        )	
        return lista  


class listEmpleadoByKword(ListView):
    """Lista empleados por palabra clave"""
    template_name='persona/by_kword.html'
    context_object_name='empleados'

    def get_queryset(self):
        print('*****************************')
        palabra_clave=self.request.GET.get("kword",'')
        print('=======',palabra_clave)
        lista=Empleado.objects.filter(
            first_name =palabra_clave
        )
        print('lista resultado :',lista)
        return lista



class HabilidadesEmpleado(ListView):
    
    template_name = "persona/habilidades.html"
    context_object_name='habilidades'

    def get_queryset(self):
        empleado=Empleado.objects.get(id=1)
        print(empleado.habilidades.all())
        
        return empleado.habilidades.all()



class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"

    def get_context_data(self,**kwargs):
        context = super(EmpleadoDetailView,self).get_context_data(**kwargs)

        context['titulo']='Empleado del Mes'
        return context


 
class SuccessView(TemplateView):
    template_name = "persona/success.html"


class EmpleadoCreateView(CreateView):
    template_name = "persona/add.html"
    model = Empleado
    form_class=EmpleadoForm
    
    success_url= reverse_lazy('persona_app:empleados_admin')

    def form_valid(self, form):
        """Aca validamos los datos del form. si queremos algo mas despues del guardado"""
        
        empleado = form.save(commit=False)
        print(empleado)
        empleado.full_name= empleado.first_name+ ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView,self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    template_name = "persona/update.html"
    model = Empleado
    fields=['first_name','last_name','job','departamento','habilidades']
    success_url= reverse_lazy('persona_app:empleados_admin')


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('****************+++++MENTODO POST++++++++*********************')
        print('**************************************************************')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)


    def form_valid(self, form):
        """Aca validamos los datos del form. si queremos algo mas despues del guardado"""
        print('****************+++++MENTODO FORM_VALID++++++++*********************')
        print('**************************************************************')
        
        return super(EmpleadoUpdateView,self).form_valid(form)


class EmpleadoDeleteView(DeleteView):
    template_name = "persona/delete.html"
    model = Empleado
    
    fields=['first_name','last_name','job','departamento','habilidades']
    success_url= reverse_lazy('persona_app:empleados_admin')


class ListaEmpleadosAdmin(ListView):
    template_name='persona/lista_empleados.html'
    paginate_by=10
    ordering='first_name'
    model=Empleado
    context_object_name='empleados'
    

templates/persona/add.html
{% extends 'base.html' %}


{% block title %}
    Registrar Empleado
    
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}
    <div class="grid-contrainer">
        
        <div class="grid-x">
            
            <h1 class="cell">Registrar Persona</h1>
            
            
            <form  class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
                
                <div class="medium-6 cell">
                    <label>Nombres:
                        {{form.first_name}}
                      
                    </label>
                </div>

                <div class="medium-6 cell">
                    <label>Apellidos:
                        {{form.last_name}}
                      
                    </label>
                </div>

                <div class="medium-6 cell">
                    <label>Trabajo:
                        {{form.job}}
                      
                    </label>
                </div>

                <div class="medium-6 cell">
                    <label>Departamento:
                        {{form.departamento}}
                      
                    </label>
                </div>

                <div class="medium-12 cell">
                    <label>Habilidades Extra:
                        {{form.habilidades}}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <label>Foto:
                        {{form.avatar}}
                    </label>
                </div>

                <div class="cell">
                    <button type="submit" class="success button">Guardar</button>

                </div>
            </form>
            
        </div>


    </div>





{% endblock content %}

templates/persona/by_kword.html
<h1>Buscar Empelado por palabra clave</h1>

<form  method="get">{% csrf_token %}

    <input type="text" id="kword" name="kword" placeholder="Ingrese nombre">
    <button type="submit" >Buscar</button>
</form>

<h3>Lista Resulados</h3>
<ul>
    {% for e in empleados %}
        <li>{{e}}</li>
        
    {% endfor %}



</ul>


    

templates/persona/delete.html
{% extends 'base.html' %}


{% block title %}
    Eliminar Empleado
    
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}


<div class="grid-container">

    <div class="grid-x">



        <h1 class="cell">Eliminar Empleado : {{object.first_name}}  {{object.last_name}}</h1>

    
        <form class="cell" method="post"> {% csrf_token %}

            <div class="callout large">
                <h5>¿Desea eliminar este Empleado?</h5>
                
                <button type="submit" class="alert button">Confirmar</button>
                
            </div>
            
        </form>

    </div>



</div>

   


    
{% endblock content %}
    

templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{object.name}}
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}

        <div class="grid-contrainer">
                
            <div class="grid-x grid-margin-x align-center">
                
                <div class="cell large-4 card" style="width: 300px;">
                    <div class="card-divider">
                        {{empleado.get_job_display}}
                    </div>
                    
                    {% if empleado.avatar %}
                        <img src="{{empleado.avatar.url}}">
                        

                    {% else %}

                        <img src="{% static 'img/30.jpg' %}">

                    {% endif %}
                         
                    
                    <div class="card-section">
                        <h4>{{empleado.first_name}} {{empleado.last_name}}</h4>
                        <p>{{empleado.departamento.shor_name}}</p>
                        
                        <p><span class="label">Habilidades</span></p>
                        <ul class="vertical menu"></ul>
                            
                            {% for h in empleado.habilidades.all %}
                                <li>{{h.habilidad}}</li>
                                
                                
                            {% endfor %}
                                
                    </div>
                </div>
            </div>
        </div>
        
        <form  class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
            
            <div class="medium-6 cell">

{% endblock content %}

templates/persona/habilidades.html
<h1>Habilidades</h1>

<ul>

    
    {% for h in habilidades %}
        <li>{{h}}</li>
    {% endfor %}
           


</ul>

templates/persona/list_all.html
{% extends 'base.html' %}
{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">

   <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="get">{% csrf_token %}
            
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="Buscar Empleado">
            </div>     
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>

            <div class="cell">
                <table>
                    <thead>
                      <tr>

                        <th width="200">ID</th>
                        <th width="200">NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">FULL NAME</th>
                        <th width="150">ACCION</th>

                        
                      </tr>
                    </thead>

                    <tbody>
                        {% for e in empleados  %}
                        
                    
                        <tr>

                            <td>{{e.id}}</td>
                            <td>{{e.first_name}}</td>
                            <td>{{e.last_name}}</td>
                            <td>{{e.departamento}}</td>
                            <td>{{e.full_name}}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>



                        </tr>
                        {% endfor %}
                    </tbody>
                  </table>
    
            </div>

        <div class="cell">

            
            {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous enabled"><a href="?page={{page_obj.previous_page_number}}" aria-label="Previous page">Atras <span class="show-for-sr">page</span></a></li>
                        {% endif %}


                        
                        {% for pagina in paginator.page_range  %}
                            
                            {% ifequal  pagina page_obj.number  %} 
                                
                                <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
                                
                            {% else %}
                                <li><a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li>
                            {% endifequal %}
                                


                            
                        {% endfor %}
                            
                            
                        
                        
                        
                        {% if page_obj.has_next %}
                            <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Siguiente <span class="show-for-sr">page</span></a></li>

                        {% endif %}
                            
                        
                    </ul>
                </nav>
            {% endif %}
                
            
        </div>

   </div> 
    
</div>



{% endblock content %}
    

templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}
    lista empleados por departamento
{% endblock title %}
    

{% block content %}
    {% include 'includes/header.html' %}


    <div class="grid-container">
        <div class="grid-x">
            <div class="cell"> Empleados por Area:</div>
                <div class="cell">
                <table>
                    <thead>
                      <tr>

                        <th width="200">ID</th>
                        <th width="200">NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">FULL NAME</th>
                        <th width="150">ACCION</th>

                        
                      </tr>
                    </thead>

                    <tbody>
                        {% for e in empleados  %}
                        
                    
                            <tr>

                                <td>{{e.id}}</td>
                                <td>{{e.first_name}}</td>
                                <td>{{e.last_name}}</td>
                                <td>{{e.departamento}}</td>
                                <td>{{e.full_name}}</td>
                                <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>



                            </tr>
                        {% endfor %}
                    </tbody>
                  </table>
            
                </div>

        </div>


    </div>
    
{% endblock content %}
    
<ul>

    
    {% for e in empleados  %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul>

templates/persona/lista_empleados.html
{% extends 'base.html' %}

{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <td>
                            <a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a>
                        </td>
                        <td>
                            <a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% endif %}
                    
                    {% for pagina in paginator.page_range %}

                    
                    {% ifequal pagina page_obj.number %}
                    <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                    {% else %}
                    <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>
                    {% endifequal %}
                    {% endfor %}
                    
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/persona/success.html
<h1>Felicitacion se guardó correctamente el Empleado</h1>

templates/persona/update.html
{% extends 'base.html' %}


{% block title %}
    Editar Empleado
    
{% endblock title %}


{% block content %}

    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x ">

            <h1 class="cell"> Modificar Empleado</h1>
            <div class="cell">

                <form class="grid-x grid-margin-x" method="POST"> {% csrf_token %}
                    <div class="cell large-6">
                        <label>Nombres:
                            {{form.first_name}}
                          
                        </label>
                    </div>

                    <div class="cell large-6">
                        <label>Apellidos:
                            {{form.last_name}}
                        </label>
                    </div>

                    <div class="cell large-6">
                        <label>Trabajo:
                            {{form.job}}
                        </label>
                    </div>

                    <div class="cell large-6">
                        <label>Area:
                            {{form.departamento}}
                        </label>
                    </div>

                    <div class="cell">
                        <label>Habilidades Extra:
                            {{form.habilidades}}
                        </label>
                    </div>

                    <div class="cell">
                        <button type="submit" class="success button">Guardar</button>

                    </div>

                </form>

            </div>

        </div>


    </div>



    



{% endblock content %}



    